[tool.isort]
profile = "black"

[tool.pylint]
disable = [
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "redefined-outer-name",
]
max-line-length = 88

[tool.pyright]
typeCheckingMode = "strict"
