from unittest import TestCase

from day11 import expand, parse, sum_diffs

UNEXPANDED = parse(
    """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
    """.strip()
)
EXPANDED = parse(
    """
....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
    """.strip()
)


class TestGalaxy(TestCase):
    def test_sub(self):
        self.assertEqual(EXPANDED[4] - EXPANDED[8], 9)
        self.assertEqual(EXPANDED[0] - EXPANDED[6], 15)
        self.assertEqual(EXPANDED[2] - EXPANDED[5], 17)
        self.assertEqual(EXPANDED[7] - EXPANDED[8], 5)


class Test(TestCase):
    def test_expand(self):
        self.assertEqual(expand(UNEXPANDED), EXPANDED)

    def test_sum_diffs(self):
        self.assertEqual(sum_diffs(EXPANDED), 374)


class IntegrationTest(TestCase):
    def test(self):
        self.assertEqual(sum_diffs(expand(UNEXPANDED)), 374)
        self.assertEqual(sum_diffs(expand(UNEXPANDED, 10)), 1030)
        self.assertEqual(sum_diffs(expand(UNEXPANDED, 100)), 8410)
